# is the name of the Workflow in the Github actions.
name: first-workflow
# push event
on: [push]
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.6.9
      - name: Check Version
        run: python --version
